

name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies & run tests
              working-directory: app
              run: |
                npm ci
                npm test

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.9.5
            
            - name: tflint
              uses: terraform-linters/setup-tflint@v4
            - run: |
                tflint --init
                tflint --chdir infra

            - name: tfsec
              uses: aquasecurity/tfsec-action@v1
              with:
                working_directory: infra

            - name: Validate Terraform
              working-directory: infra
              run: |
                terraform init -backend=false
                terraform fmt -check
                terraform validate
