name: Deploy (No-AWS Test)

on:
  workflow_run:
    workflows: [ CI ]
    types: [completed]
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      sha:
        description: "Commit HEAD"
        required: false

env:
  COMMIT_SHA: ${{ github.event_name == 'workflow_dispatch'
                  && (github.event.inputs.sha || github.sha)
                  || github.event.workflow_run.head_sha }}

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: registry
    env:
      IMAGE_NAME: ci-cd-demo-app
      IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-demo-app
   
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          ref: ${{ env.COMMIT_SHA }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      # 3) Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build and push docker image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.COMMIT_SHA }}
            ${{ env.IMAGE_REPO }}:latest
          cache-from: ${{ !env.ACT && 'type=gha' || '' }}
          cache-to: ${{ !env.ACT && 'type=gha,mode=max' || '' }}

  plan:
    needs: build_and_push
    runs-on: ubuntu-latest
    environment: registry

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform init/validate
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate

      - name: Terraform plan
        working-directory: infra
        run: |
          terraform plan \
            -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" \
            -var="image_name=ci-cd-demo-app" \
            -var="image_tag=${COMMIT_SHA}" \
            -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform init (same backend mode as plan)
        working-directory: infra
        run: terraform init -backend=false

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra

      - name: Terraform apply
        working-directory: infra
        run: terraform apply -auto-approve tfplan
