name: Deploy (No-AWS Test)

on:
  workflow_run:
    workflows: [ CI ]
    types: [completed]
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: deployment
    env:
      IMAGE_NAME: node-demo-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      # 1) Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG ./app
             docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aws-ci-cd-demo:${{ github.sha }} ./app

      # 2) Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Login to Docker Hub
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aws-ci-cd-demo:${{ github.sha }}
          docker tag  ${{ secrets.DOCKERHUB_USERNAME }}/aws-ci-cd-demo:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/aws-ci-cd-demo:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aws-ci-cd-demo:latest

      # 4) Run container in the runner (fake deploy) + health check
      - name: Run container
        run: |
          docker run -d --name demo -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG
          # wait for it to come up
          for i in {1..20}; do
            sleep 1
            if curl -sf http://localhost:8080 >/dev/null; then
              echo "App is up"; break
            fi
            echo "Waiting for app..."
          done
          # final health assertion
          curl -sS http://localhost:8080 | tee response.txt
          grep -q "Hello" response.txt

      - name: Show running containers
        run: docker ps

      # 5) Terraform (plan-only) to test IaC pipeline bits
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt/validate
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate

      - name: Terraform plan (no backend, no apply)
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/tfplan

      # 5) Cleanup container (keep the runner clean)
      - name: Cleanup
        if: always()
        run: |
          docker rm -f demo || true

