name: Deploy (No-AWS Test)

on:
  workflow_run:
    workflows: [ CI ]
    types: [completed]
    branches: [ "main" ]

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: deployment
    env:
      IMAGE_NAME: ci-cd-demo-app
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-demo-app
   
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: $IMAGE_TAG

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      # 3) Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build and push docker image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            $IMAGE_REPO:$IMAGE_TAG
            $IMAGE_REPO:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  plan:
    needs: build_and_push
    runs-on: ubuntu-latest
    environment: deployment
    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Checkout commit
        uses: ctions/checkout@v4
        with:
          ref: $IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform init/validate
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate

      - name: Terraform plan
        working-directory: infra
        run: |
          terraform plan \
            -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" \
            -var="image_name=ci-cd-demo-app" \
            -var="image_tag=${IMAGE_TAG}" \
            -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: deployment
    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: $IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Download plan
        uses: action/download-artifact@v4
        with:
          name: tfplan
          path: infra

      - name: Terraform apply
        working-directory: infra
        run: terraform apply -auto-pprove tfplan
